### ISSUE TITLE
在拉取最新版本代码后，代码中出现了导包错误

### ISSUE THREAD

**Issue by polaris0915** [uozi-tech/cosy#3]
![2512261733108131_ pic](https://github.com/user-attachments/assets/3d8cdbeb-6425-402c-87c3-d3639d78a918)

![2512271733108131_ pic](https://github.com/user-attachments/assets/c52ea271-05f6-4793-b598-26b126e3f025)
![2512281733108131_ pic](https://github.com/user-attachments/assets/25bba7ac-8ed9-4f30-83bd-f520bbc1cb7f)
![2512291733108131_ pic](https://github.com/user-attachments/assets/a079e3b8-0446-455a-b505-9207eb67c648)

在拉取最新版本的代码之后，用vscode打开之后就会出现导入"github.com/elliotchance/orderedmap/v2"错误。
然后我点进去发现是无法导入官方的“iter”包。

这个应该怎么解决，感谢了，很想学习整个工具都是怎么实现的

**Comment by 0xJacky** [comment]
Vscode 当前环境执行 go version 输出的是 1.23.2 吗？

**Comment by polaris0915** [comment]
是的。

这是我的go环境的信息：

(base) alin-youlinlin@ALin-youlinlindeMacBook-Pro cosy-main % go version
go version go1.23.2 darwin/amd64
(base) alin-youlinlin@ALin-youlinlindeMacBook-Pro cosy-main % go env
GO111MODULE='on'
GOARCH='amd64'
GOBIN=''
GOCACHE='/Users/alin-youlinlin/Library/Caches/go-build'
GOENV='/Users/alin-youlinlin/Library/Application Support/go/env'
GOEXE=''
GOEXPERIMENT=''
GOFLAGS=''
GOHOSTARCH='amd64'
GOHOSTOS='darwin'
GOINSECURE=''
GOMODCACHE='/Users/alin-youlinlin/go/pkg/mod'
GONOPROXY=''
GONOSUMDB=''
GOOS='darwin'
GOPATH='/Users/alin-youlinlin/go'
GOPRIVATE=''
GOPROXY='https://goproxy.cn,direct'
GOROOT='/Users/alin-youlinlin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-amd64'
GOSUMDB='sum.golang.org'
GOTMPDIR=''
GOTOOLCHAIN='auto'
GOTOOLDIR='/Users/alin-youlinlin/go/pkg/mod/golang.org/toolchain@v0.0.1-go1.23.2.darwin-amd64/pkg/tool/darwin_amd64'
GOVCS=''
GOVERSION='go1.23.2'
GODEBUG=''
GOTELEMETRY='local'
GOTELEMETRYDIR='/Users/alin-youlinlin/Library/Application Support/go/telemetry'
GCCGO='gccgo'
GOAMD64='v1'
AR='ar'
CC='clang'
CXX='clang++'
CGO_ENABLED='1'
GOMOD='/Users/alin-youlinlin/Desktop/GitHub/cosy-main/go.mod'
GOWORK=''
CGO_CFLAGS='-O2 -g'
CGO_CPPFLAGS=''
CGO_CXXFLAGS='-O2 -g'
CGO_FFLAGS='-O2 -g'
CGO_LDFLAGS='-O2 -g'
PKG_CONFIG='pkg-config'
GOGCCFLAGS='-fPIC -arch x86_64 -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -ffile-prefix-map=/var/folders/pr/mbwp61q158lg1w3zk2nbxm400000gn/T/go-build3948148209=/tmp/go-build -gno-record-gcc-switches -fno-common'
(base) alin-youlinlin@ALin-youlinlindeMacBook-Pro cosy-main %

**Comment by 0xJacky** [comment]
我这边用 VSCode 也试了一下，没法复现，不过这个问题应该不是代码层面的，试试

```
go clean -modcache
go mod tidy
```

**Comment by polaris0915** [comment]
清除了也是没有用。问题貌似是无法导入官方的iter包导致那个orderedmap导入也出现错误

刚换了goland是没有问题的。暂且先这样子吧。之后再看看到底应该怎么解决
感谢感谢，您有微信或者别的联系方式么

**Comment by 0xJacky** [comment]
不好意思啊，不玩微信的😂

**Comment by polaris0915** [comment]
好的好的，感谢感谢
