### ISSUE TITLE
项目实现建议

### ISSUE THREAD

**Issue by polaris0915** [uozi-tech/cosy#6]
请问您我想实现一下您整个这个项目应该从哪里着手，能否提供一些建议或者思路。谢谢了！

**Comment by 0xJacky** [comment]
您是指重新写一遍这个项目？

**Comment by polaris0915** [comment]
对的，我想大体的实现一遍。能提供思路嘛

**Comment by 0xJacky** [comment]
核心思路就是，增删改查，写多了，发现很多东西都是可以抽出来的，然后用 hook 的方式来实现特殊的功能。这个可以看一下文档的流程图。

**Comment by polaris0915** [comment]
那些文档的流程图我都看过了，总的来说我现在是不知道从哪里着手开始。我应该尝试从哪个模块开始，第一次来git上学习项目，有点迷糊。

**Comment by 0xJacky** [comment]
你好，这个我只能点到为止，多谢理解。

**Comment by polaris0915** [comment]
谢谢
