### ISSUE TITLE
关于数据库驱动的结偶分离问题

### ISSUE THREAD

**Issue by polaris0915** [uozi-tech/cosy#7]
model.go文件中Init函数传入的参数“dialect gorm.Dialector”。我又看了一下源代码。这个“dialect gorm.Dialector”是靠“github.com/uozi-tech/cosy-driver-mysql”这个第三方库来得倒一个"gorm.Dialector"类型的变量之后传入Init函数的。那么问题来了，为什么c您要这么做呢。不能直接嵌入到model模块中么？

是只是为了解耦让model模块的功能独立于关于数据库的实现么？

**Comment by 0xJacky** [comment]
因为用的 gorm，model.Init 函数需要调用 gorm.Open

https://github.com/uozi-tech/cosy/blob/f740cb08e1deea196b9583eb2d34b62ec1c02425/model/model.go#L51

第一个参数就是接受的  gorm.Dialector

这样做是为了能扩展不同的数据库驱动，比如 MySQL, PostgreSQL，SQLite 等。

**Comment by 0xJacky** [comment]
Cosy 的诞生就是为了减少通用代码的重复编写工作。关于你提到的这个情况，是我们早期在使用的方案，现在已经统一并抽离到 Cosy 中了。

**Comment by polaris0915** [comment]
OKOK，谢谢解答。我继续领悟一下
